# Playbook to install the newrelic agent on a machine
#
# ansible-playbook install-newrelic.yml -e newrelic_license_key=$NEWRELIC_LICENSE_KEY

# - name: Update apt-get repo and cache
#   apt: 
#     name: update_cache=yes


- name:  NewRelic repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://download.newrelic.com/infrastructure_agent/linux/apt hirsute main
    state: present
    update_cache: yes



- name: NewRelic | Add GPG key to the apt sources keyring
  ansible.builtin.apt_key:
    url: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
    state: present
    update_cache: yes


- name: NewRelic | Add license key in the config file
  ansible.builtin.lineinfile:
        path: /etc/newrelic-infra.yml
        regexp: '^license_key: {{ newrelic_license_key }}'
        line: 'license_key: {{ newrelic_license_key }}'
        state: present


- name: newrelic-infra
  apt:
    name: newrelic-infra
    state: present
    update_cache: yes
