
- name: NewRelic | Add license key in the config file
  ansible.builtin.lineinfile:
        path: /etc/newrelic-infra.yml
        # regexp: '^license_key: {{ newrelic_license_key }}'
        line: 'license_key: {{ newrelic_license_key }}'
        state: present

# - name: NewRelic | Add license key in the config file
#   ansible.builtin.lineinfile:
#     path: /etc/newrelic-infra.yml
#     regexp: '^license_key='
#     line: 'license_key: 98EB3EF710396C7003FF60EC6400D8203BE701845B67BF906D8422F18A3803A6


- name: NewRelic | Add GPG key to the apt sources keyring
  ansible.builtin.apt_key:
    url: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
    state: present



- name:  NewRelic repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://download.newrelic.com/infrastructure_agent/linux/apt hirsute main
    state: present


- name: newrelic-infra
  apt:
    name: newrelic-infra
    state: present
    update_cache: yes