- name: NewRelic | Add license key in the config file
  lineinfile:
        path: /etc/newrelic-infra.yml
        regexp: '^license_key: {{ newrelic_license_key }}'
        line: 'license_key: {{ newrelic_license_key }}'
        state: present
 

- name: NewRelic | Add GPG key to the apt sources keyring
  apt_key:
    url: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
    state: present

- name:  NewRelic repository into sources list
  apt_repository:
    repo: deb https://download.newrelic.com/infrastructure_agent/linux/apt focal main
    state: present


- name: newrelic-infra
  apt:
    name: newrelic-infra
    state: present
    update_cache: yes
