- name: To update
  apt:
    update_cache: yes

- name: NewRelic | Add apt sources list
  apt_repository:
        repo: deb [arch=amd64] https://download.newrelic.com/infrastructure_agent/linux/apt hirsute main
        state: present


- name: NewRelic | Add GPG key to the apt sources keyring
  apt_key:
        url: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
        state: present
  
- name: NewRelic | Add license key in the config file
  lineinfile:
        path: /etc/newrelic-infra.yml
        regexp: '^license_key: {{ newrelic_license_key }}'
        line: 'license_key: {{ newrelic_license_key }}'
        state: present
      

- name: NewRelic | Run the install command
  apt: pkg=newrelic-infra update_cache=yes

- name: NewRelic | Check that NewRelic service is started
  systemd:
        name: newrelic-infra
        state: started
        enabled: True